version: '3.8'

services:
  bot:
    build: .
    container_name: fast_save_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads # Чтобы файлы не пропадали внутри контейнера
